name: Clean notebooks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install tools
        run: |
          pip install nbconvert nbstripout
      - name: Strip notebook metadata
        run: |
          find . -name "*.ipynb" -print0 | xargs -0 -I{} \
            jupyter nbconvert --to notebook --inplace "{}" --ClearMetadataPreprocessor.enabled=True
      - name: Auto-commit cleaned notebooks
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-clean notebook metadata"
          file_pattern: "*.ipynb"
